// SUMMONER'S JOURNAL - CRITICAL LEARNINGS ONLY
// Format: ## YYYY-MM-DD - [Seed] Gap: [No Wizard avatar] Summon: [Added wizard_female.png mapping]
// ## 2024-05-22 - [Seed] Gap: Missing Paladin/Monk archetypes and a cold-themed campaign. Summon: Added Sir Alistair, Morgana, Kael, and 'The Frozen Expanse' campaign.
// ## 2025-02-18 - [Seed] Gap: Limited high-level intrigue campaign. Summon: Added 'The Crimson Citadel' with Lord Blackthorn and Lady Vespera.
// ## 2025-05-23 - [Seed] Gap: No aquatic themed campaign. Summon: Added 'The Sunken City' with Captain Saltbeard and Marina.
// ## 2025-05-24 - [Seed] Gap: No tournament or arena style campaign. Summon: Added 'The Gilded Tournament' with Grandmaster Thorne and Champion Urga.
// ## 2025-05-25 - [Seed] Gap: No underground/dwarven themed campaign. Summon: Added 'The Iron Depths' with King Thorgar and Guide Brilda.
// ## 2025-05-26 - [Seed] Gap: No high-magic feywild campaign. Summon: Added 'The Whispering Woods' with Elara and Thalin.
// ## 2025-05-27 - [Seed] Gap: No undead/cleric themed campaign. Summon: Added 'Catacombs of the Faithful' with High Priestess Anara and Cult Leader Malos.
// ## 2025-05-28 - [Seed] Gap: No desert/wasteland themed campaign. Summon: Added 'The Scorched Wastes' with Kaelen and Mirage Weaver.
// ## 2025-05-29 - [Seed] Gap: No jungle/beast themed campaign. Summon: Added 'The Verdant Jungle' with Kaelith and Spirit of the Wilds.
// ## 2025-05-29 - [Seed] Gap: No steampunk/clockwork themed campaign. Summon: Added 'The Clockwork City' with Cogsworth and Ironclad.
// ## 2025-05-30 - [Seed] Gap: No sky/air themed campaign. Summon: Added 'The Floating Isles' with Captain Zephyr and Aeris.

import 'dotenv/config'
import { prisma } from '../src/lib/prisma'
import fs from 'fs'
import path from 'path'

// Define a template for character creation
interface CharacterTemplate {
  name: string
  type: 'PLAYER' | 'NPC'
  race: string
  class: string
  imageUrl: string
  hp: number
  maxHp: number
  armorClass: number
  initiative: number // Static bonus
  initiativeRoll: number // Initial roll for fun
  speed: number
  attributes: Record<string, number>
  activeTurn: boolean
  level?: number
}

const libraryCharacters: CharacterTemplate[] = [
  // --- Existing Characters ---
  {
    name: 'Galus Gallow',
    type: 'PLAYER',
    race: 'Human',
    class: 'Ranger',
    imageUrl: '/avatars/human_archer_male_1770268315511.png',
    hp: 11,
    maxHp: 11,
    armorClass: 14,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 9, dex: 16, con: 13, int: 11, wis: 14, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Commander Samuel Vimes',
    type: 'PLAYER',
    race: 'Human',
    class: 'Fighter',
    imageUrl: '/avatars/fighter_male_1770266290109.png', // Rugged fighter
    hp: 13,
    maxHp: 13,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 10, con: 16, int: 9, wis: 14, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Marco The Gallant',
    type: 'PLAYER',
    race: 'Human',
    class: 'Bard',
    imageUrl: '/avatars/bard_male_1770267480087.png',
    hp: 10,
    maxHp: 10,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 9, dex: 15, con: 14, int: 11, wis: 13, cha: 16 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Elara Lightbringer',
    type: 'PLAYER',
    race: 'Human',
    class: 'Cleric',
    imageUrl: '/avatars/cleric_female_1770266235967.png',
    hp: 10,
    maxHp: 10,
    armorClass: 16,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 12, dex: 10, con: 13, int: 10, wis: 16, cha: 13 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Thrain Ironfoot',
    type: 'PLAYER',
    race: 'Dwarf',
    class: 'Fighter',
    imageUrl: '/avatars/dwarf_fighter_male_1770268439402.png',
    hp: 14,
    maxHp: 14,
    armorClass: 17,
    initiative: -1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 16, dex: 8, con: 17, int: 10, wis: 12, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Sylph Leafshade',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Ranger',
    imageUrl: '/avatars/elf_archer_female_1770268263008.png',
    hp: 10,
    maxHp: 10,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 17, con: 12, int: 12, wis: 14, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Pip the Prankster',
    type: 'PLAYER',
    race: 'Tiefling',
    class: 'Rogue',
    imageUrl: '/avatars/jester_male_1770267240604.png',
    hp: 9,
    maxHp: 9,
    armorClass: 14,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 16, con: 12, int: 13, wis: 10, cha: 15 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Grommash',
    type: 'PLAYER',
    race: 'Half-Orc',
    class: 'Barbarian',
    imageUrl: '/avatars/fantasy_barbarian_male_1770266807624.png',
    hp: 15,
    maxHp: 15,
    armorClass: 14,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 17, dex: 12, con: 16, int: 8, wis: 10, cha: 9 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Brother Marcus',
    type: 'PLAYER',
    race: 'Human',
    class: 'Cleric',
    imageUrl: '/avatars/cleric_male_1770266221119.png',
    hp: 11,
    maxHp: 11,
    armorClass: 16,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 13, dex: 10, con: 14, int: 10, wis: 16, cha: 12 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Seraphina',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Rogue',
    imageUrl: '/avatars/rogue_female_1770266208126.png',
    hp: 9,
    maxHp: 9,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 18, con: 11, int: 13, wis: 10, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Rosie',
    type: 'PLAYER',
    race: 'Hobbit',
    class: 'Druid',
    imageUrl: '/avatars/hobbit_female_1770268009102.png',
    hp: 8,
    maxHp: 8,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 8, dex: 14, con: 12, int: 12, wis: 16, cha: 13 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Flint Fireforge',
    type: 'PLAYER',
    race: 'Dwarf',
    class: 'Mage',
    imageUrl: '/avatars/dwarf_mage_male_1770268698293.png',
    hp: 9,
    maxHp: 9,
    armorClass: 11,
    initiative: 1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 10, dex: 12, con: 16, int: 17, wis: 12, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Arin',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Fighter',
    imageUrl: '/avatars/elf_fighter_male_1770268090822.png',
    hp: 12,
    maxHp: 12,
    armorClass: 16,
    initiative: 3,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 14, dex: 16, con: 12, int: 12, wis: 11, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Huntress Diana',
    type: 'PLAYER',
    race: 'Human',
    class: 'Archer',
    imageUrl: '/avatars/human_archer_female_1770268333890.png',
    hp: 10,
    maxHp: 10,
    armorClass: 15,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 11, dex: 16, con: 12, int: 10, wis: 14, cha: 12 },
    activeTurn: false,
    level: 1,
  },
  // --- New Additions ---
  {
    name: 'Kaelith Stormwind',
    type: 'PLAYER',
    race: 'Human',
    class: 'Barbarian',
    imageUrl: '/avatars/barbarian_archer_female_1770268298470.png',
    hp: 14,
    maxHp: 14,
    armorClass: 14,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 14, con: 15, int: 8, wis: 10, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Thorgar the Fierce',
    type: 'PLAYER',
    race: 'Human',
    class: 'Barbarian',
    imageUrl: '/avatars/barbarian_archer_male_1770268280543.png',
    hp: 15,
    maxHp: 15,
    armorClass: 14,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 17, dex: 12, con: 16, int: 8, wis: 10, cha: 9 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Lila the Lark',
    type: 'PLAYER',
    race: 'Half-Elf',
    class: 'Bard',
    imageUrl: '/avatars/bard_female_1770267498918.png',
    hp: 9,
    maxHp: 9,
    armorClass: 12,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 12, int: 12, wis: 10, cha: 17 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Thora Stonebow',
    type: 'PLAYER',
    race: 'Dwarf',
    class: 'Ranger',
    imageUrl: '/avatars/dwarf_archer_female_1770268683214.png',
    hp: 12,
    maxHp: 12,
    armorClass: 14,
    initiative: 2,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 12, dex: 14, con: 14, int: 10, wis: 14, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Borin Ironshot',
    type: 'PLAYER',
    race: 'Dwarf',
    class: 'Ranger',
    imageUrl: '/avatars/dwarf_archer_male_1770268667839.png',
    hp: 13,
    maxHp: 13,
    armorClass: 14,
    initiative: 1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 13, dex: 12, con: 16, int: 10, wis: 14, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Silas Greenleaf',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Ranger',
    imageUrl: '/avatars/elf_archer_male_1770268242137.png',
    hp: 10,
    maxHp: 10,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 17, con: 11, int: 12, wis: 15, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Elara Moonshadow',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Druid',
    imageUrl: '/avatars/elf_female_1770267651052.png',
    hp: 9,
    maxHp: 9,
    armorClass: 11,
    initiative: 2,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 8, dex: 14, con: 10, int: 12, wis: 16, cha: 13 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Lyra Starborn',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Sorcerer',
    imageUrl: '/avatars/elf_female_1770267798836.png',
    hp: 8,
    maxHp: 8,
    armorClass: 12,
    initiative: 3,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 8, dex: 14, con: 12, int: 10, wis: 10, cha: 17 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Vanya Blade',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Fighter',
    imageUrl: '/avatars/elf_fighter_female_1770268107753.png',
    hp: 11,
    maxHp: 11,
    armorClass: 15,
    initiative: 3,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 12, dex: 16, con: 12, int: 11, wis: 10, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Finnegan Swift',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Rogue',
    imageUrl: '/avatars/elf_male_1770267781103.png',
    hp: 9,
    maxHp: 9,
    armorClass: 14,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 17, con: 10, int: 13, wis: 10, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Captain Varya',
    type: 'PLAYER',
    race: 'Human',
    class: 'Fighter',
    imageUrl: '/avatars/fighter_female_1770266152007.png',
    hp: 13,
    maxHp: 13,
    armorClass: 16,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 12, con: 14, int: 10, wis: 12, cha: 12 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Bingo Boffin',
    type: 'PLAYER',
    race: 'Hobbit',
    class: 'Rogue',
    imageUrl: '/avatars/hobbit_male_1770267994027.png',
    hp: 8,
    maxHp: 8,
    armorClass: 13,
    initiative: 3,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 8, dex: 16, con: 12, int: 10, wis: 10, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Samwise Gamgee',
    type: 'PLAYER',
    race: 'Hobbit',
    class: 'Druid',
    imageUrl: '/avatars/hobbit_male_1770268037843.png',
    hp: 9,
    maxHp: 9,
    armorClass: 12,
    initiative: 1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 10, dex: 12, con: 14, int: 10, wis: 16, cha: 12 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Trixie',
    type: 'PLAYER',
    race: 'Tiefling',
    class: 'Jester',
    imageUrl: '/avatars/jester_female_1770267550485.png',
    hp: 10,
    maxHp: 10,
    armorClass: 13,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 16, con: 12, int: 10, wis: 8, cha: 16 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Garrett',
    type: 'PLAYER',
    race: 'Human',
    class: 'Thief',
    imageUrl: '/avatars/thief_male_1770267752047.png',
    hp: 9,
    maxHp: 9,
    armorClass: 13,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 16, con: 10, int: 12, wis: 10, cha: 13 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Shadow Dancer',
    type: 'PLAYER',
    race: 'Human',
    class: 'Rogue',
    imageUrl: '/avatars/thief_female_1770267766244.png',
    hp: 9,
    maxHp: 9,
    armorClass: 14,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 17, con: 10, int: 11, wis: 10, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Sir Alistair',
    type: 'PLAYER',
    race: 'Human',
    class: 'Paladin',
    imageUrl: '/avatars/fighter_male_1770266139273.png',
    hp: 12,
    maxHp: 12,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 10, con: 14, int: 10, wis: 14, cha: 15 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Morgana',
    type: 'PLAYER',
    race: 'Human',
    class: 'Warlock',
    imageUrl: '/avatars/wizard_female_1770266180583.png',
    hp: 9,
    maxHp: 9,
    armorClass: 12,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 12, int: 13, wis: 10, cha: 16 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Kael',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Monk',
    imageUrl: '/avatars/elf_fighter_male_1770268090822.png',
    hp: 10,
    maxHp: 10,
    armorClass: 16,
    initiative: 4,
    initiativeRoll: 0,
    speed: 40,
    attributes: { str: 10, dex: 17, con: 12, int: 10, wis: 15, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Krix',
    type: 'PLAYER',
    race: 'Goblin',
    class: 'Rogue',
    imageUrl: '/avatars/rogue_male_1770266194878.png',
    hp: 8,
    maxHp: 8,
    armorClass: 13,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 16, con: 12, int: 10, wis: 10, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Zara',
    type: 'PLAYER',
    race: 'Genasi',
    class: 'Sorcerer',
    imageUrl: '/avatars/nymph_female_1770267925456.png',
    hp: 9,
    maxHp: 9,
    armorClass: 12,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 14, con: 12, int: 10, wis: 12, cha: 16 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Brother Kael',
    type: 'PLAYER',
    race: 'Human',
    class: 'Monk',
    imageUrl: '/avatars/cleric_male_1770266221119.png',
    hp: 10,
    maxHp: 10,
    armorClass: 14,
    initiative: 3,
    initiativeRoll: 0,
    speed: 40,
    attributes: { str: 12, dex: 16, con: 12, int: 10, wis: 16, cha: 10, Ki: 2 },
    activeTurn: false,
    level: 2,
  },
  // --- Generic NPCs ---
  {
    name: 'Orc Raider',
    type: 'NPC',
    race: 'Orc',
    class: 'Barbarian',
    imageUrl: '/avatars/fantasy_barbarian_male_1770266807624.png',
    hp: 15,
    maxHp: 15,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 12, con: 14, int: 8, wis: 10, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Elven Scout',
    type: 'NPC',
    race: 'Elf',
    class: 'Ranger',
    imageUrl: '/avatars/elf_archer_male_1770268242137.png',
    hp: 12,
    maxHp: 12,
    armorClass: 14,
    initiative: 3,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 16, con: 12, int: 12, wis: 14, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Dwarven Defender',
    type: 'NPC',
    race: 'Dwarf',
    class: 'Fighter',
    imageUrl: '/avatars/dwarf_fighter_male_1770268439402.png',
    hp: 18,
    maxHp: 18,
    armorClass: 16,
    initiative: 1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 14, dex: 10, con: 16, int: 10, wis: 12, cha: 10 },
    activeTurn: false,
    level: 2,
  },
]

const campaignCharacters: CharacterTemplate[] = [
  {
    name: 'Valerius the Brave',
    type: 'PLAYER',
    race: 'Human',
    class: 'Paladin',
    imageUrl: '/avatars/fighter_male_1770266139273.png',
    hp: 28,
    maxHp: 32,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 15,
    speed: 30,
    attributes: { str: 16, dex: 10, con: 14, int: 10, wis: 12, cha: 15 },
    activeTurn: true,
    level: 3,
  },
  {
    name: 'Lyra Moonwhisper',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Wizard',
    imageUrl: '/avatars/wizard_female_1770266180583.png',
    hp: 12,
    maxHp: 18,
    armorClass: 12,
    initiative: 2,
    initiativeRoll: 22,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 12, int: 17, wis: 13, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Goblin Grunt',
    type: 'NPC',
    race: 'Goblin',
    class: 'Scout',
    imageUrl: '/avatars/rogue_male_1770266194878.png',
    hp: 7,
    maxHp: 7,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 8,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Matriarch Zog',
    type: 'NPC',
    race: 'Orc',
    class: 'Barbarian',
    imageUrl: '/avatars/fantasy_barbarian_female_1770266826511.png',
    hp: 45,
    maxHp: 45,
    armorClass: 15,
    initiative: 1,
    initiativeRoll: 12,
    speed: 35,
    attributes: { str: 18, dex: 12, con: 16, int: 9, wis: 11, cha: 14 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Bandit Thug',
    type: 'NPC',
    race: 'Human',
    class: 'Rogue',
    imageUrl: '/avatars/thief_male_1770267828895.png',
    hp: 16,
    maxHp: 16,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 10,
    speed: 30,
    attributes: { str: 12, dex: 14, con: 12, int: 10, wis: 10, cha: 10 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Fae Wisp',
    type: 'NPC',
    race: 'Fairy',
    class: 'Sorcerer',
    imageUrl: '/avatars/fairy_female_1770267946577.png',
    hp: 12,
    maxHp: 12,
    armorClass: 14,
    initiative: 4,
    initiativeRoll: 18,
    speed: 40,
    attributes: { str: 4, dex: 18, con: 10, int: 12, wis: 14, cha: 16 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Elder Thaddeus',
    type: 'NPC',
    race: 'Human',
    class: 'Wizard',
    imageUrl: '/avatars/wizard_male_1770266164795.png',
    hp: 22,
    maxHp: 22,
    armorClass: 11,
    initiative: 1,
    initiativeRoll: 6,
    speed: 25,
    attributes: { str: 8, dex: 10, con: 10, int: 18, wis: 16, cha: 12 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Nerida',
    type: 'NPC',
    race: 'Nymph',
    class: 'Druid',
    imageUrl: '/avatars/nymph_female_1770267925456.png',
    hp: 18,
    maxHp: 18,
    armorClass: 12,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 16, con: 10, int: 12, wis: 16, cha: 18 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Sergeant Brutus',
    type: 'NPC',
    race: 'Human',
    class: 'Fighter',
    imageUrl: '/avatars/fighter_male_1770266261627.png',
    hp: 25,
    maxHp: 25,
    armorClass: 16,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 12, con: 14, int: 10, wis: 10, cha: 12 },
    activeTurn: false,
    level: 3,
  },
  // --- New Additions ---
  {
    name: 'Archmage Solus',
    type: 'NPC',
    race: 'Human',
    class: 'Wizard',
    imageUrl: '/avatars/fantasy_wizard_male_1770266844095.png',
    hp: 40,
    maxHp: 40,
    armorClass: 15,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 14, int: 20, wis: 16, cha: 14 },
    activeTurn: false,
    level: 10,
  },
  {
    name: 'Sylvanus',
    type: 'NPC',
    race: 'Nymph',
    class: 'Druid',
    imageUrl: '/avatars/nymph_male_1770267906487.png',
    hp: 22,
    maxHp: 22,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 14, con: 12, int: 12, wis: 18, cha: 16 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Nightshade',
    type: 'NPC',
    race: 'Human',
    class: 'Rogue',
    imageUrl: '/avatars/thief_female_1770267844778.png',
    hp: 18,
    maxHp: 18,
    armorClass: 14,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 18, con: 12, int: 12, wis: 10, cha: 14 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Eldrin Highmoon',
    type: 'NPC',
    race: 'Elf',
    class: 'Noble',
    imageUrl: '/avatars/elf_male_1770267634807.png',
    hp: 10,
    maxHp: 10,
    armorClass: 11,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 12, con: 10, int: 14, wis: 12, cha: 16 },
    activeTurn: false,
    level: 1,
  },
]

const citadelCharacters: CharacterTemplate[] = [
  {
    name: 'Lord Blackthorn',
    type: 'NPC',
    race: 'Human',
    class: 'Fighter',
    imageUrl: '/avatars/fighter_male_1770266261627.png',
    hp: 45,
    maxHp: 45,
    armorClass: 17,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 18, dex: 12, con: 16, int: 12, wis: 14, cha: 16 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Lady Vespera',
    type: 'NPC',
    race: 'Elf',
    class: 'Sorcerer',
    imageUrl: '/avatars/wizard_female_1770266180583.png',
    hp: 30,
    maxHp: 30,
    armorClass: 12,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 12, int: 14, wis: 12, cha: 18 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Pogo',
    type: 'NPC',
    race: 'Tiefling',
    class: 'Bard',
    imageUrl: '/avatars/jester_male_1770267240604.png',
    hp: 15,
    maxHp: 15,
    armorClass: 13,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 16, con: 12, int: 10, wis: 8, cha: 16 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Sir Gideon',
    type: 'NPC',
    race: 'Human',
    class: 'Paladin',
    imageUrl: '/avatars/fighter_male_1770266139273.png',
    hp: 28,
    maxHp: 28,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 10, con: 14, int: 10, wis: 12, cha: 14 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Innkeeper Bessie',
    type: 'NPC',
    race: 'Human',
    class: 'Commoner',
    imageUrl: '/avatars/bard_female_1770267498918.png',
    hp: 10,
    maxHp: 10,
    armorClass: 10,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 10, con: 10, int: 10, wis: 14, cha: 12 },
    activeTurn: false,
    level: 1,
  },
]

const sunkenCityCharacters: CharacterTemplate[] = [
  {
    name: 'Captain Saltbeard',
    type: 'NPC',
    race: 'Human',
    class: 'Pirate',
    imageUrl: '/avatars/fighter_male_1770266290109.png',
    hp: 40,
    maxHp: 40,
    armorClass: 15,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 14, con: 16, int: 12, wis: 14, cha: 16 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Marina the Mystic',
    type: 'PLAYER',
    race: 'Water Genasi',
    class: 'Sorcerer',
    imageUrl: '/avatars/nymph_female_1770267925456.png',
    hp: 25,
    maxHp: 25,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 14, con: 14, int: 12, wis: 14, cha: 18 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Deep Sea Diver',
    type: 'NPC',
    race: 'Dwarf',
    class: 'Artificer',
    imageUrl: '/avatars/dwarf_fighter_male_1770268439402.png',
    hp: 35,
    maxHp: 35,
    armorClass: 16,
    initiative: 1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 14, dex: 12, con: 16, int: 16, wis: 12, cha: 10 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Siren',
    type: 'NPC',
    race: 'Siren',
    class: 'Bard',
    imageUrl: '/avatars/elf_female_1770267651052.png',
    hp: 20,
    maxHp: 20,
    armorClass: 12,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 16, con: 12, int: 12, wis: 14, cha: 18 },
    activeTurn: false,
    level: 3,
  }
]

const tournamentCharacters: CharacterTemplate[] = [
  {
    name: 'Grandmaster Thorne',
    type: 'NPC',
    race: 'Human',
    class: 'Fighter',
    imageUrl: '/avatars/fighter_male_1770266290109.png',
    hp: 50,
    maxHp: 50,
    armorClass: 16,
    initiative: 5,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 18, dex: 14, con: 16, int: 14, wis: 14, cha: 16 },
    activeTurn: false,
    level: 10,
  },
  {
    name: 'Champion Urga',
    type: 'NPC',
    race: 'Orc',
    class: 'Barbarian',
    imageUrl: '/avatars/fantasy_barbarian_female_1770266826511.png',
    hp: 45,
    maxHp: 45,
    armorClass: 15,
    initiative: 2,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 20, dex: 12, con: 18, int: 8, wis: 10, cha: 12 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Zola the Announcer',
    type: 'NPC',
    race: 'Tiefling',
    class: 'Bard',
    imageUrl: '/avatars/jester_female_1770267550485.png',
    hp: 20,
    maxHp: 20,
    armorClass: 12,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 14, con: 12, int: 14, wis: 12, cha: 18 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Swiftshot',
    type: 'NPC',
    race: 'Elf',
    class: 'Ranger',
    imageUrl: '/avatars/elf_archer_male_1770268242137.png',
    hp: 25,
    maxHp: 25,
    armorClass: 16,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 12, dex: 18, con: 12, int: 10, wis: 14, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Sir Gallant',
    type: 'PLAYER',
    race: 'Human',
    class: 'Paladin',
    imageUrl: '/avatars/fighter_male_1770266139273.png',
    hp: 30,
    maxHp: 30,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 10, con: 14, int: 10, wis: 12, cha: 16 },
    activeTurn: true,
    level: 3,
  },
]

const ironDepthsCharacters: CharacterTemplate[] = [
  {
    name: 'King Thorgar',
    type: 'NPC',
    race: 'Dwarf',
    class: 'Fighter',
    imageUrl: '/avatars/dwarf_fighter_male_1770268439402.png',
    hp: 45,
    maxHp: 45,
    armorClass: 17,
    initiative: 2,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 18, dex: 12, con: 16, int: 10, wis: 14, cha: 16 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Guide Brilda',
    type: 'NPC',
    race: 'Dwarf',
    class: 'Ranger',
    imageUrl: '/avatars/dwarf_archer_female_1770268683214.png',
    hp: 24,
    maxHp: 24,
    armorClass: 14,
    initiative: 3,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 12, dex: 16, con: 14, int: 10, wis: 14, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Scholar Orin',
    type: 'NPC',
    race: 'Dwarf',
    class: 'Wizard',
    imageUrl: '/avatars/dwarf_mage_male_1770268698293.png',
    hp: 18,
    maxHp: 18,
    armorClass: 11,
    initiative: 1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 10, dex: 12, con: 14, int: 16, wis: 12, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Deep Gnome Spy',
    type: 'NPC',
    race: 'Gnome',
    class: 'Rogue',
    imageUrl: '/avatars/hobbit_male_1770267994027.png',
    hp: 14,
    maxHp: 14,
    armorClass: 13,
    initiative: 4,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 8, dex: 16, con: 12, int: 14, wis: 10, cha: 10 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Cave Troll',
    type: 'NPC',
    race: 'Troll',
    class: 'Monster',
    imageUrl: '/avatars/fantasy_barbarian_male_1770266807624.png',
    hp: 60,
    maxHp: 60,
    armorClass: 14,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 20, dex: 10, con: 18, int: 6, wis: 8, cha: 6 },
    activeTurn: false,
    level: 5,
  }
]

const whisperingWoodsCharacters: CharacterTemplate[] = [
  {
    name: 'Elara the Guardian',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Fighter',
    imageUrl: '/avatars/elf_fighter_female_1770268107753.png',
    hp: 20,
    maxHp: 20,
    armorClass: 16,
    initiative: 3,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 14, dex: 16, con: 12, int: 11, wis: 14, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Thalin Swiftbow',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Ranger',
    imageUrl: '/avatars/elf_archer_female_1770268263008.png',
    hp: 18,
    maxHp: 18,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 18, con: 12, int: 12, wis: 14, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Pip',
    type: 'NPC',
    race: 'Fairy',
    class: 'Guide',
    imageUrl: '/avatars/fairy_female_1770267946577.png',
    hp: 10,
    maxHp: 10,
    armorClass: 14,
    initiative: 5,
    initiativeRoll: 0,
    speed: 40,
    attributes: { str: 4, dex: 20, con: 10, int: 12, wis: 14, cha: 16 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Elder Mossbeard',
    type: 'NPC',
    race: 'Treant',
    class: 'Druid',
    imageUrl: '/avatars/nymph_male_1770267906487.png',
    hp: 40,
    maxHp: 40,
    armorClass: 16,
    initiative: 0,
    initiativeRoll: 0,
    speed: 20,
    attributes: { str: 18, dex: 8, con: 18, int: 14, wis: 18, cha: 12 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Malakor the Rot',
    type: 'NPC',
    race: 'Elf',
    class: 'Necromancer',
    imageUrl: '/avatars/elf_male_1770267781103.png',
    hp: 35,
    maxHp: 35,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 14, con: 14, int: 16, wis: 12, cha: 10 },
    activeTurn: false,
    level: 5,
  }
]

const catacombsCharacters: CharacterTemplate[] = [
  {
    name: 'High Priestess Anara',
    type: 'PLAYER',
    race: 'Human',
    class: 'Cleric',
    imageUrl: '/avatars/cleric_female_1770266235967.png',
    hp: 35,
    maxHp: 35,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 12, dex: 10, con: 14, int: 12, wis: 18, cha: 14 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Brother Thomas',
    type: 'PLAYER',
    race: 'Human',
    class: 'Cleric',
    imageUrl: '/avatars/cleric_male_1770266221119.png',
    hp: 28,
    maxHp: 28,
    armorClass: 16,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 14, dex: 10, con: 14, int: 10, wis: 16, cha: 12 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Sir Kaelen',
    type: 'PLAYER',
    race: 'Human',
    class: 'Paladin',
    imageUrl: '/avatars/fighter_male_1770266139273.png',
    hp: 42,
    maxHp: 42,
    armorClass: 19,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 18, dex: 10, con: 16, int: 10, wis: 12, cha: 14 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Grave Robber',
    type: 'NPC',
    race: 'Human',
    class: 'Rogue',
    imageUrl: '/avatars/thief_male_1770267752047.png',
    hp: 18,
    maxHp: 18,
    armorClass: 14,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 16, con: 12, int: 10, wis: 10, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Cult Leader Malos',
    type: 'NPC',
    race: 'Human',
    class: 'Warlock',
    imageUrl: '/avatars/wizard_male_1770266164795.png',
    hp: 45,
    maxHp: 45,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 14, int: 12, wis: 10, cha: 18 },
    activeTurn: false,
    level: 6,
  }
]

const scorchedWastesCharacters: CharacterTemplate[] = [
  {
    name: 'Kaelen Sunstrider',
    type: 'PLAYER',
    race: 'Human',
    class: 'Paladin',
    imageUrl: '/avatars/fighter_male_1770266261627.png',
    hp: 32,
    maxHp: 32,
    armorClass: 18,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 12, con: 14, int: 10, wis: 14, cha: 12 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Elara Sandborn',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Ranger',
    imageUrl: '/avatars/elf_archer_female_1770268263008.png',
    hp: 28,
    maxHp: 28,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 18, con: 12, int: 12, wis: 14, cha: 8 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Desert Nomad',
    type: 'NPC',
    race: 'Human',
    class: 'Scout',
    imageUrl: '/avatars/thief_male_1770267828895.png',
    hp: 18,
    maxHp: 18,
    armorClass: 14,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 12, dex: 16, con: 14, int: 10, wis: 12, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Scorpion King',
    type: 'NPC',
    race: 'Monstrosity',
    class: 'Boss',
    imageUrl: '/avatars/fantasy_barbarian_male_1770266807624.png',
    hp: 65,
    maxHp: 65,
    armorClass: 16,
    initiative: 2,
    initiativeRoll: 0,
    speed: 40,
    attributes: { str: 20, dex: 14, con: 18, int: 8, wis: 12, cha: 10 },
    activeTurn: false,
    level: 6,
  },
  {
    name: 'Mirage Weaver',
    type: 'NPC',
    race: 'Genasi',
    class: 'Sorcerer',
    imageUrl: '/avatars/nymph_male_1770267906487.png',
    hp: 35,
    maxHp: 35,
    armorClass: 13,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 14, int: 12, wis: 10, cha: 18 },
    activeTurn: false,
    level: 5,
  }
]

const verdantJungleCharacters: CharacterTemplate[] = [
  {
    name: 'Kaelith the Wild',
    type: 'PLAYER',
    race: 'Human',
    class: 'Ranger',
    imageUrl: '/avatars/barbarian_archer_female_1770268298470.png',
    hp: 25,
    maxHp: 25,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 14, dex: 16, con: 14, int: 10, wis: 14, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Thorgar Ironhide',
    type: 'PLAYER',
    race: 'Human',
    class: 'Barbarian',
    imageUrl: '/avatars/barbarian_archer_male_1770268280543.png',
    hp: 32,
    maxHp: 32,
    armorClass: 14,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 18, dex: 12, con: 16, int: 8, wis: 12, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Spirit of the Wilds',
    type: 'NPC',
    race: 'Nymph',
    class: 'Sorcerer',
    imageUrl: '/avatars/nymph_female_1770267925456.png',
    hp: 20,
    maxHp: 20,
    armorClass: 12,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 14, con: 12, int: 12, wis: 16, cha: 18 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Goblin Trapper',
    type: 'NPC',
    race: 'Goblin',
    class: 'Ranger',
    imageUrl: '/avatars/rogue_male_1770266194878.png',
    hp: 12,
    maxHp: 12,
    armorClass: 13,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 16, con: 10, int: 12, wis: 10, cha: 8 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Snake Cultist',
    type: 'NPC',
    race: 'Human',
    class: 'Warlock',
    imageUrl: '/avatars/wizard_male_1770266164795.png',
    hp: 18,
    maxHp: 18,
    armorClass: 11,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 12, con: 10, int: 14, wis: 10, cha: 16 },
    activeTurn: false,
    level: 3,
  }
]

const clockworkCityCharacters: CharacterTemplate[] = [
  {
    name: 'Cogsworth',
    type: 'PLAYER',
    race: 'Gnome',
    class: 'Artificer',
    imageUrl: '/avatars/hobbit_male_1770267994027.png',
    hp: 22,
    maxHp: 22,
    armorClass: 14,
    initiative: 2,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 8, dex: 14, con: 14, int: 18, wis: 10, cha: 12 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Ironclad',
    type: 'NPC',
    race: 'Warforged',
    class: 'Fighter',
    imageUrl: '/avatars/dwarf_fighter_male_1770268439402.png',
    hp: 35,
    maxHp: 35,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 18, dex: 10, con: 18, int: 10, wis: 10, cha: 8 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Gear-Mistress Vyla',
    type: 'NPC',
    race: 'Human',
    class: 'Rogue',
    imageUrl: '/avatars/thief_female_1770267766244.png',
    hp: 24,
    maxHp: 24,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 18, con: 12, int: 16, wis: 12, cha: 14 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Mad Tinkerer',
    type: 'NPC',
    race: 'Dwarf',
    class: 'Wizard',
    imageUrl: '/avatars/dwarf_mage_male_1770268698293.png',
    hp: 30,
    maxHp: 30,
    armorClass: 12,
    initiative: 2,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 10, dex: 12, con: 14, int: 18, wis: 14, cha: 8 },
    activeTurn: false,
    level: 5,
  }
]

const floatingIslesCharacters: CharacterTemplate[] = [
  {
    name: 'Captain Zephyr',
    type: 'PLAYER',
    race: 'Human',
    class: 'Sky Captain',
    imageUrl: '/avatars/human_archer_male_1770268315511.png',
    hp: 25,
    maxHp: 25,
    armorClass: 16,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 12, dex: 16, con: 12, int: 12, wis: 14, cha: 16 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Aeris',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Wind Mage',
    imageUrl: '/avatars/elf_female_1770267651052.png',
    hp: 18,
    maxHp: 18,
    armorClass: 12,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 12, int: 18, wis: 14, cha: 12 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Sky Pirate Vane',
    type: 'NPC',
    race: 'Human',
    class: 'Rogue',
    imageUrl: '/avatars/thief_male_1770267752047.png',
    hp: 20,
    maxHp: 20,
    armorClass: 14,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 16, con: 12, int: 12, wis: 10, cha: 14 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Nimbus',
    type: 'NPC',
    race: 'Storm Giant',
    class: 'Barbarian',
    imageUrl: '/avatars/fantasy_barbarian_male_1770266807624.png',
    hp: 60,
    maxHp: 60,
    armorClass: 16,
    initiative: 1,
    initiativeRoll: 0,
    speed: 40,
    attributes: { str: 22, dex: 10, con: 20, int: 10, wis: 12, cha: 10 },
    activeTurn: false,
    level: 6,
  },
  {
    name: 'Wind Elemental',
    type: 'NPC',
    race: 'Elemental',
    class: 'Spirit',
    imageUrl: '/avatars/nymph_female_1770267925456.png',
    hp: 30,
    maxHp: 30,
    armorClass: 14,
    initiative: 5,
    initiativeRoll: 0,
    speed: 50,
    attributes: { str: 10, dex: 20, con: 14, int: 8, wis: 12, cha: 10 },
    activeTurn: false,
    level: 4,
  }
]

async function main() {
  console.log('🕯️ Summoner: Starting seed process...')

  // Clear existing data
  await prisma.logEntry.deleteMany()
  await prisma.character.deleteMany()
  await prisma.campaign.deleteMany()
  await prisma.encounter.deleteMany()

  console.log('🧹 Cleared existing data.')

  // Create Library Campaign (Inactive)
  const library = await prisma.campaign.create({
    data: {
      name: 'Character Library',
      active: false,
      characters: {
        create: libraryCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      }
    }
  })

  console.log(`📚 Created Library with ${libraryCharacters.length} presets.`)

  // Create Active Campaign
  const campaign = await prisma.campaign.create({
    data: {
      name: 'The Shadow of Everdawn',
      active: true,
      characters: {
        create: campaignCharacters.map((char) => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        })),
      },
      logs: {
        create: [
          { content: 'The world of **The Shadow of Everdawn** is born.', type: 'Story' },
          { content: 'Campaign started in the Whispering Woods.', type: 'Story' },
          { content: 'Valerius rolled a **15** for initiative!', type: 'Roll' },
          { content: 'A group of goblins led by **Matriarch Zog** ambushes the party!', type: 'Combat' },
          { content: '**Matriarch Zog** roars, rallying her minions!', type: 'Story' },
          { content: '**Fae Wisp** flutters nervously above the fray.', type: 'Story' },
        ],
      },
    },
  })

  console.log(`🎉 Campaign "${campaign.name}" created with ${campaignCharacters.length} characters.`)

  // Create The Frozen Expanse Campaign (Inactive)
  const frozenCampaign = await prisma.campaign.create({
    data: {
      name: 'The Frozen Expanse',
      active: false,
      characters: {
        create: [
          {
            name: 'Bjorn',
            type: 'PLAYER',
            race: 'Human',
            class: 'Barbarian',
            imageUrl: '/avatars/fantasy_barbarian_male_1770266807624.png',
            hp: 20,
            maxHp: 20,
            armorClass: 14,
            initiative: 1,
            initiativeRoll: 0,
            speed: 30,
            attributes: JSON.stringify({ str: 18, dex: 12, con: 16, int: 8, wis: 10, cha: 10 }),
            activeTurn: false,
            level: 3,
          },
          {
            name: 'Lyra',
            type: 'PLAYER',
            race: 'Elf',
            class: 'Sorcerer',
            imageUrl: '/avatars/elf_female_1770267798836.png',
            hp: 14,
            maxHp: 14,
            armorClass: 12,
            initiative: 2,
            initiativeRoll: 0,
            speed: 30,
            attributes: JSON.stringify({ str: 8, dex: 14, con: 12, int: 10, wis: 10, cha: 18 }),
            activeTurn: false,
            level: 3,
          },
          {
            name: 'Ice Construct',
            type: 'NPC',
            race: 'Construct',
            class: 'Guardian',
            imageUrl: '/avatars/dwarf_mage_male_1770268698293.png',
            hp: 30,
            maxHp: 30,
            armorClass: 16,
            initiative: 0,
            initiativeRoll: 0,
            speed: 20,
            attributes: JSON.stringify({ str: 18, dex: 8, con: 18, int: 3, wis: 10, cha: 1 }),
            activeTurn: false,
            level: 4,
          },
          {
            name: 'Town Elder',
            type: 'NPC',
            race: 'Human',
            class: 'Commoner',
            imageUrl: '/avatars/wizard_male_1770266164795.png',
            hp: 8,
            maxHp: 8,
            armorClass: 10,
            initiative: 0,
            initiativeRoll: 0,
            speed: 30,
            attributes: JSON.stringify({ str: 9, dex: 10, con: 10, int: 14, wis: 16, cha: 12 }),
            activeTurn: false,
            level: 1,
          },
        ]
      },
      logs: {
        create: [
          { content: 'The winds howl across **The Frozen Expanse**.', type: 'Story' },
          { content: '**Bjorn** and **Lyra** arrive at the remote outpost.', type: 'Story' },
          { content: 'A strange **Ice Construct** blocks the path ahead.', type: 'Combat' },
        ]
      }
    }
  })

  console.log(`❄️ Campaign "${frozenCampaign.name}" created.`)

  // Create The Crimson Citadel Campaign (Inactive)
  const citadelCampaign = await prisma.campaign.create({
    data: {
      name: 'The Crimson Citadel',
      active: false,
      characters: {
        create: citadelCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'The iron gates of **The Crimson Citadel** loom before you.', type: 'Story' },
          { content: '**Lord Blackthorn** watches from the high tower.', type: 'Story' },
          { content: '**Lady Vespera** whispers arcane secrets in the shadows.', type: 'Story' },
          { content: 'A distinct lack of hospitality greets the party.', type: 'Story' },
        ]
      }
    }
  })

  console.log(`🏰 Campaign "${citadelCampaign.name}" created.`)

  // Create The Sunken City Campaign (Inactive)
  const sunkenCityCampaign = await prisma.campaign.create({
    data: {
      name: 'The Sunken City',
      active: false,
      characters: {
        create: sunkenCityCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'The waves crash against the hull of the **Sea Serpent**.', type: 'Story' },
          { content: '**Captain Saltbeard** barks orders at the crew.', type: 'Story' },
          { content: 'A beautiful song drifts from the rocky shoals...', type: 'Story' },
        ]
      }
    }
  })

  console.log(`🌊 Campaign "${sunkenCityCampaign.name}" created.`)

  // Create The Gilded Tournament Campaign (Inactive)
  const tournamentCampaign = await prisma.campaign.create({
    data: {
      name: 'The Gilded Tournament',
      active: false,
      characters: {
        create: tournamentCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'Welcome to **The Gilded Tournament**!', type: 'Story' },
          { content: '**Zola the Announcer** amplifies her voice with magic.', type: 'Story' },
          { content: '**Grandmaster Thorne** observes from his throne.', type: 'Story' },
          { content: '**Champion Urga** flexes her muscles, intimidating the crowd.', type: 'Story' },
        ]
      }
    }
  })

  console.log(`⚔️ Campaign "${tournamentCampaign.name}" created.`)

  // Create The Iron Depths Campaign (Inactive)
  const ironDepthsCampaign = await prisma.campaign.create({
    data: {
      name: 'The Iron Depths',
      active: false,
      characters: {
        create: ironDepthsCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'The tunnels of **The Iron Depths** echo with ancient machinery.', type: 'Story' },
          { content: '**King Thorgar** leads the expedition into the dark.', type: 'Story' },
          { content: '**Scholar Orin** studies the glowing runes on the wall.', type: 'Story' },
          { content: 'A deep rumble shakes the cavern floor...', type: 'Story' },
        ]
      }
    }
  })

  console.log(`⚒️ Campaign "${ironDepthsCampaign.name}" created.`)

  // Create The Whispering Woods Campaign (Inactive)
  const whisperingWoodsCampaign = await prisma.campaign.create({
    data: {
      name: 'The Whispering Woods',
      active: false,
      characters: {
        create: whisperingWoodsCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'The ancient canopy of **The Whispering Woods** blocks out the sun.', type: 'Story' },
          { content: '**Elara the Guardian** detects a disturbance in the ley lines.', type: 'Story' },
          { content: '**Pip** giggles as she leads the group astray.', type: 'Story' },
          { content: 'A sinister fog begins to roll in from the north...', type: 'Story' },
        ]
      }
    }
  })

  console.log(`🍃 Campaign "${whisperingWoodsCampaign.name}" created.`)

  // Create Catacombs of the Faithful Campaign (Inactive)
  const catacombsCampaign = await prisma.campaign.create({
    data: {
      name: 'Catacombs of the Faithful',
      active: false,
      characters: {
        create: catacombsCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'The air in the **Catacombs of the Faithful** is thick with incense and decay.', type: 'Story' },
          { content: '**High Priestess Anara** raises her holy symbol against the dark.', type: 'Story' },
          { content: '**Brother Thomas** tends to the wounded.', type: 'Story' },
          { content: '**Cult Leader Malos** chants a forbidden ritual in the distance...', type: 'Story' },
        ]
      }
    }
  })

  console.log(`💀 Campaign "${catacombsCampaign.name}" created.`)

  // Create The Scorched Wastes Campaign (Inactive)
  const scorchedWastesCampaign = await prisma.campaign.create({
    data: {
      name: 'The Scorched Wastes',
      active: false,
      characters: {
        create: scorchedWastesCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'The relentless sun beats down on **The Scorched Wastes**.', type: 'Story' },
          { content: '**Kaelen Sunstrider** shields his eyes from the glare.', type: 'Story' },
          { content: 'A mirage shimmers in the distance... or is it the **Mirage Weaver**?', type: 'Story' },
          { content: 'The ground trembles as the **Scorpion King** awakens.', type: 'Story' },
        ]
      }
    }
  })

  console.log(`🌵 Campaign "${scorchedWastesCampaign.name}" created.`)

  // Create The Verdant Jungle Campaign (Inactive)
  const verdantJungleCampaign = await prisma.campaign.create({
    data: {
      name: 'The Verdant Jungle',
      active: false,
      characters: {
        create: verdantJungleCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'The canopy of **The Verdant Jungle** teems with life and danger.', type: 'Story' },
          { content: '**Kaelith the Wild** tracks a beast through the undergrowth.', type: 'Story' },
          { content: '**Thorgar Ironhide** roars a challenge to the wilderness.', type: 'Story' },
          { content: 'A pair of glowing eyes watches from the shadows...', type: 'Story' },
        ]
      }
    }
  })

  console.log(`🌿 Campaign "${verdantJungleCampaign.name}" created.`)

  // Create The Clockwork City Campaign (Inactive)
  const clockworkCityCampaign = await prisma.campaign.create({
    data: {
      name: 'The Clockwork City',
      active: false,
      characters: {
        create: clockworkCityCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'The gears of **The Clockwork City** never stop turning.', type: 'Story' },
          { content: '**Cogsworth** makes a final adjustment to his gadget.', type: 'Story' },
          { content: '**Ironclad** stands guard at the factory gates.', type: 'Story' },
          { content: 'The **Mad Tinkerer** laughs maniacally from his lab.', type: 'Story' },
        ]
      }
    }
  })

  console.log(`⚙️ Campaign "${clockworkCityCampaign.name}" created.`)

  // Create The Floating Isles Campaign (Inactive)
  const floatingIslesCampaign = await prisma.campaign.create({
    data: {
      name: 'The Floating Isles',
      active: false,
      characters: {
        create: floatingIslesCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      },
      logs: {
        create: [
          { content: 'The winds howl through the rigging of the **Sky Skimmer**.', type: 'Story' },
          { content: '**Captain Zephyr** steadies the helm.', type: 'Story' },
          { content: '**Aeris** summons a gust to propel the ship forward.', type: 'Story' },
          { content: 'A massive shadow passes overhead... **Nimbus** approaches.', type: 'Story' },
        ]
      }
    }
  })

  console.log(`☁️ Campaign "${floatingIslesCampaign.name}" created.`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
