// SUMMONER'S JOURNAL - CRITICAL LEARNINGS ONLY
// Format: ## YYYY-MM-DD - [Seed] Gap: [No Wizard avatar] Summon: [Added wizard_female.png mapping]
// ## 2024-05-22 - [Seed] Gap: Missing Paladin/Monk archetypes and a cold-themed campaign. Summon: Added Sir Alistair, Morgana, Kael, and 'The Frozen Expanse' campaign.

import 'dotenv/config'
import { prisma } from '../src/lib/prisma'
import fs from 'fs'
import path from 'path'

// Define a template for character creation
interface CharacterTemplate {
  name: string
  type: 'PLAYER' | 'NPC'
  race: string
  class: string
  imageUrl: string
  hp: number
  maxHp: number
  armorClass: number
  initiative: number // Static bonus
  initiativeRoll: number // Initial roll for fun
  speed: number
  attributes: Record<string, number>
  activeTurn: boolean
  level?: number
}

const libraryCharacters: CharacterTemplate[] = [
  // --- Existing Characters ---
  {
    name: 'Galus Gallow',
    type: 'PLAYER',
    race: 'Human',
    class: 'Ranger',
    imageUrl: '/avatars/human_archer_male_1770268315511.png',
    hp: 11,
    maxHp: 11,
    armorClass: 14,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 9, dex: 16, con: 13, int: 11, wis: 14, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Commander Samuel Vimes',
    type: 'PLAYER',
    race: 'Human',
    class: 'Fighter',
    imageUrl: '/avatars/fighter_male_1770266290109.png', // Rugged fighter
    hp: 13,
    maxHp: 13,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 10, con: 16, int: 9, wis: 14, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Marco The Gallant',
    type: 'PLAYER',
    race: 'Human',
    class: 'Bard',
    imageUrl: '/avatars/bard_male_1770267480087.png',
    hp: 10,
    maxHp: 10,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 9, dex: 15, con: 14, int: 11, wis: 13, cha: 16 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Elara Lightbringer',
    type: 'PLAYER',
    race: 'Human',
    class: 'Cleric',
    imageUrl: '/avatars/cleric_female_1770266235967.png',
    hp: 10,
    maxHp: 10,
    armorClass: 16,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 12, dex: 10, con: 13, int: 10, wis: 16, cha: 13 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Thrain Ironfoot',
    type: 'PLAYER',
    race: 'Dwarf',
    class: 'Fighter',
    imageUrl: '/avatars/dwarf_fighter_male_1770268439402.png',
    hp: 14,
    maxHp: 14,
    armorClass: 17,
    initiative: -1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 16, dex: 8, con: 17, int: 10, wis: 12, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Sylph Leafshade',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Ranger',
    imageUrl: '/avatars/elf_archer_female_1770268263008.png',
    hp: 10,
    maxHp: 10,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 17, con: 12, int: 12, wis: 14, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Pip the Prankster',
    type: 'PLAYER',
    race: 'Tiefling',
    class: 'Rogue',
    imageUrl: '/avatars/jester_male_1770267240604.png',
    hp: 9,
    maxHp: 9,
    armorClass: 14,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 16, con: 12, int: 13, wis: 10, cha: 15 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Grommash',
    type: 'PLAYER',
    race: 'Half-Orc',
    class: 'Barbarian',
    imageUrl: '/avatars/fantasy_barbarian_male_1770266807624.png',
    hp: 15,
    maxHp: 15,
    armorClass: 14,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 17, dex: 12, con: 16, int: 8, wis: 10, cha: 9 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Brother Marcus',
    type: 'PLAYER',
    race: 'Human',
    class: 'Cleric',
    imageUrl: '/avatars/cleric_male_1770266221119.png',
    hp: 11,
    maxHp: 11,
    armorClass: 16,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 13, dex: 10, con: 14, int: 10, wis: 16, cha: 12 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Seraphina',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Rogue',
    imageUrl: '/avatars/rogue_female_1770266208126.png',
    hp: 9,
    maxHp: 9,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 18, con: 11, int: 13, wis: 10, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Rosie',
    type: 'PLAYER',
    race: 'Hobbit',
    class: 'Druid',
    imageUrl: '/avatars/hobbit_female_1770268009102.png',
    hp: 8,
    maxHp: 8,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 8, dex: 14, con: 12, int: 12, wis: 16, cha: 13 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Flint Fireforge',
    type: 'PLAYER',
    race: 'Dwarf',
    class: 'Mage',
    imageUrl: '/avatars/dwarf_mage_male_1770268698293.png',
    hp: 9,
    maxHp: 9,
    armorClass: 11,
    initiative: 1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 10, dex: 12, con: 16, int: 17, wis: 12, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Arin',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Fighter',
    imageUrl: '/avatars/elf_fighter_male_1770268090822.png',
    hp: 12,
    maxHp: 12,
    armorClass: 16,
    initiative: 3,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 14, dex: 16, con: 12, int: 12, wis: 11, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Huntress Diana',
    type: 'PLAYER',
    race: 'Human',
    class: 'Archer',
    imageUrl: '/avatars/human_archer_female_1770268333890.png',
    hp: 10,
    maxHp: 10,
    armorClass: 15,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 11, dex: 16, con: 12, int: 10, wis: 14, cha: 12 },
    activeTurn: false,
    level: 1,
  },
  // --- New Additions ---
  {
    name: 'Kaelith Stormwind',
    type: 'PLAYER',
    race: 'Human',
    class: 'Barbarian',
    imageUrl: '/avatars/barbarian_archer_female_1770268298470.png',
    hp: 14,
    maxHp: 14,
    armorClass: 14,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 14, con: 15, int: 8, wis: 10, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Thorgar the Fierce',
    type: 'PLAYER',
    race: 'Human',
    class: 'Barbarian',
    imageUrl: '/avatars/barbarian_archer_male_1770268280543.png',
    hp: 15,
    maxHp: 15,
    armorClass: 14,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 17, dex: 12, con: 16, int: 8, wis: 10, cha: 9 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Lila the Lark',
    type: 'PLAYER',
    race: 'Half-Elf',
    class: 'Bard',
    imageUrl: '/avatars/bard_female_1770267498918.png',
    hp: 9,
    maxHp: 9,
    armorClass: 12,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 12, int: 12, wis: 10, cha: 17 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Thora Stonebow',
    type: 'PLAYER',
    race: 'Dwarf',
    class: 'Ranger',
    imageUrl: '/avatars/dwarf_archer_female_1770268683214.png',
    hp: 12,
    maxHp: 12,
    armorClass: 14,
    initiative: 2,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 12, dex: 14, con: 14, int: 10, wis: 14, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Borin Ironshot',
    type: 'PLAYER',
    race: 'Dwarf',
    class: 'Ranger',
    imageUrl: '/avatars/dwarf_archer_male_1770268667839.png',
    hp: 13,
    maxHp: 13,
    armorClass: 14,
    initiative: 1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 13, dex: 12, con: 16, int: 10, wis: 14, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Silas Greenleaf',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Ranger',
    imageUrl: '/avatars/elf_archer_male_1770268242137.png',
    hp: 10,
    maxHp: 10,
    armorClass: 15,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 17, con: 11, int: 12, wis: 15, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Elara Moonshadow',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Druid',
    imageUrl: '/avatars/elf_female_1770267651052.png',
    hp: 9,
    maxHp: 9,
    armorClass: 11,
    initiative: 2,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 8, dex: 14, con: 10, int: 12, wis: 16, cha: 13 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Lyra Starborn',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Sorcerer',
    imageUrl: '/avatars/elf_female_1770267798836.png',
    hp: 8,
    maxHp: 8,
    armorClass: 12,
    initiative: 3,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 8, dex: 14, con: 12, int: 10, wis: 10, cha: 17 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Vanya Blade',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Fighter',
    imageUrl: '/avatars/elf_fighter_female_1770268107753.png',
    hp: 11,
    maxHp: 11,
    armorClass: 15,
    initiative: 3,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 12, dex: 16, con: 12, int: 11, wis: 10, cha: 10 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Finnegan Swift',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Rogue',
    imageUrl: '/avatars/elf_male_1770267781103.png',
    hp: 9,
    maxHp: 9,
    armorClass: 14,
    initiative: 4,
    initiativeRoll: 0,
    speed: 35,
    attributes: { str: 10, dex: 17, con: 10, int: 13, wis: 10, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Captain Varya',
    type: 'PLAYER',
    race: 'Human',
    class: 'Fighter',
    imageUrl: '/avatars/fighter_female_1770266152007.png',
    hp: 13,
    maxHp: 13,
    armorClass: 16,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 12, con: 14, int: 10, wis: 12, cha: 12 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Bingo Boffin',
    type: 'PLAYER',
    race: 'Hobbit',
    class: 'Rogue',
    imageUrl: '/avatars/hobbit_male_1770267994027.png',
    hp: 8,
    maxHp: 8,
    armorClass: 13,
    initiative: 3,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 8, dex: 16, con: 12, int: 10, wis: 10, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Samwise Gamgee',
    type: 'PLAYER',
    race: 'Hobbit',
    class: 'Druid',
    imageUrl: '/avatars/hobbit_male_1770268037843.png',
    hp: 9,
    maxHp: 9,
    armorClass: 12,
    initiative: 1,
    initiativeRoll: 0,
    speed: 25,
    attributes: { str: 10, dex: 12, con: 14, int: 10, wis: 16, cha: 12 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Trixie',
    type: 'PLAYER',
    race: 'Tiefling',
    class: 'Jester',
    imageUrl: '/avatars/jester_female_1770267550485.png',
    hp: 10,
    maxHp: 10,
    armorClass: 13,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 16, con: 12, int: 10, wis: 8, cha: 16 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Garrett',
    type: 'PLAYER',
    race: 'Human',
    class: 'Thief',
    imageUrl: '/avatars/thief_male_1770267752047.png',
    hp: 9,
    maxHp: 9,
    armorClass: 13,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 16, con: 10, int: 12, wis: 10, cha: 13 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Shadow Dancer',
    type: 'PLAYER',
    race: 'Human',
    class: 'Rogue',
    imageUrl: '/avatars/thief_female_1770267766244.png',
    hp: 9,
    maxHp: 9,
    armorClass: 14,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 17, con: 10, int: 11, wis: 10, cha: 14 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Sir Alistair',
    type: 'PLAYER',
    race: 'Human',
    class: 'Paladin',
    imageUrl: '/avatars/fighter_male_1770266139273.png',
    hp: 12,
    maxHp: 12,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 10, con: 14, int: 10, wis: 14, cha: 15 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Morgana',
    type: 'PLAYER',
    race: 'Human',
    class: 'Warlock',
    imageUrl: '/avatars/wizard_female_1770266180583.png',
    hp: 9,
    maxHp: 9,
    armorClass: 12,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 12, int: 13, wis: 10, cha: 16 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Kael',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Monk',
    imageUrl: '/avatars/elf_fighter_male_1770268090822.png',
    hp: 10,
    maxHp: 10,
    armorClass: 16,
    initiative: 4,
    initiativeRoll: 0,
    speed: 40,
    attributes: { str: 10, dex: 17, con: 12, int: 10, wis: 15, cha: 8 },
    activeTurn: false,
    level: 1,
  },
]

const campaignCharacters: CharacterTemplate[] = [
  {
    name: 'Valerius the Brave',
    type: 'PLAYER',
    race: 'Human',
    class: 'Paladin',
    imageUrl: '/avatars/fighter_male_1770266139273.png',
    hp: 28,
    maxHp: 32,
    armorClass: 18,
    initiative: 0,
    initiativeRoll: 15,
    speed: 30,
    attributes: { str: 16, dex: 10, con: 14, int: 10, wis: 12, cha: 15 },
    activeTurn: true,
    level: 3,
  },
  {
    name: 'Lyra Moonwhisper',
    type: 'PLAYER',
    race: 'Elf',
    class: 'Wizard',
    imageUrl: '/avatars/wizard_female_1770266180583.png',
    hp: 12,
    maxHp: 18,
    armorClass: 12,
    initiative: 2,
    initiativeRoll: 22,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 12, int: 17, wis: 13, cha: 10 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Goblin Grunt',
    type: 'NPC',
    race: 'Goblin',
    class: 'Scout',
    imageUrl: '/avatars/rogue_male_1770266194878.png',
    hp: 7,
    maxHp: 7,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 8,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    activeTurn: false,
    level: 1,
  },
  {
    name: 'Matriarch Zog',
    type: 'NPC',
    race: 'Orc',
    class: 'Barbarian',
    imageUrl: '/avatars/fantasy_barbarian_female_1770266826511.png',
    hp: 45,
    maxHp: 45,
    armorClass: 15,
    initiative: 1,
    initiativeRoll: 12,
    speed: 35,
    attributes: { str: 18, dex: 12, con: 16, int: 9, wis: 11, cha: 14 },
    activeTurn: false,
    level: 4,
  },
  {
    name: 'Bandit Thug',
    type: 'NPC',
    race: 'Human',
    class: 'Rogue',
    imageUrl: '/avatars/thief_male_1770267828895.png',
    hp: 16,
    maxHp: 16,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 10,
    speed: 30,
    attributes: { str: 12, dex: 14, con: 12, int: 10, wis: 10, cha: 10 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Fae Wisp',
    type: 'NPC',
    race: 'Fairy',
    class: 'Sorcerer',
    imageUrl: '/avatars/fairy_female_1770267946577.png',
    hp: 12,
    maxHp: 12,
    armorClass: 14,
    initiative: 4,
    initiativeRoll: 18,
    speed: 40,
    attributes: { str: 4, dex: 18, con: 10, int: 12, wis: 14, cha: 16 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Elder Thaddeus',
    type: 'NPC',
    race: 'Human',
    class: 'Wizard',
    imageUrl: '/avatars/wizard_male_1770266164795.png',
    hp: 22,
    maxHp: 22,
    armorClass: 11,
    initiative: 1,
    initiativeRoll: 6,
    speed: 25,
    attributes: { str: 8, dex: 10, con: 10, int: 18, wis: 16, cha: 12 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Nerida',
    type: 'NPC',
    race: 'Nymph',
    class: 'Druid',
    imageUrl: '/avatars/nymph_female_1770267925456.png',
    hp: 18,
    maxHp: 18,
    armorClass: 12,
    initiative: 3,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 16, con: 10, int: 12, wis: 16, cha: 18 },
    activeTurn: false,
    level: 2,
  },
  {
    name: 'Sergeant Brutus',
    type: 'NPC',
    race: 'Human',
    class: 'Fighter',
    imageUrl: '/avatars/fighter_male_1770266261627.png',
    hp: 25,
    maxHp: 25,
    armorClass: 16,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 16, dex: 12, con: 14, int: 10, wis: 10, cha: 12 },
    activeTurn: false,
    level: 3,
  },
  // --- New Additions ---
  {
    name: 'Archmage Solus',
    type: 'NPC',
    race: 'Human',
    class: 'Wizard',
    imageUrl: '/avatars/fantasy_wizard_male_1770266844095.png',
    hp: 40,
    maxHp: 40,
    armorClass: 15,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 14, con: 14, int: 20, wis: 16, cha: 14 },
    activeTurn: false,
    level: 10,
  },
  {
    name: 'Sylvanus',
    type: 'NPC',
    race: 'Nymph',
    class: 'Druid',
    imageUrl: '/avatars/nymph_male_1770267906487.png',
    hp: 22,
    maxHp: 22,
    armorClass: 13,
    initiative: 2,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 14, con: 12, int: 12, wis: 18, cha: 16 },
    activeTurn: false,
    level: 5,
  },
  {
    name: 'Nightshade',
    type: 'NPC',
    race: 'Human',
    class: 'Rogue',
    imageUrl: '/avatars/thief_female_1770267844778.png',
    hp: 18,
    maxHp: 18,
    armorClass: 14,
    initiative: 4,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 10, dex: 18, con: 12, int: 12, wis: 10, cha: 14 },
    activeTurn: false,
    level: 3,
  },
  {
    name: 'Eldrin Highmoon',
    type: 'NPC',
    race: 'Elf',
    class: 'Noble',
    imageUrl: '/avatars/elf_male_1770267634807.png',
    hp: 10,
    maxHp: 10,
    armorClass: 11,
    initiative: 1,
    initiativeRoll: 0,
    speed: 30,
    attributes: { str: 8, dex: 12, con: 10, int: 14, wis: 12, cha: 16 },
    activeTurn: false,
    level: 1,
  },
]

async function main() {
  console.log('🕯️ Summoner: Starting seed process...')

  // Clear existing data
  await prisma.logEntry.deleteMany()
  await prisma.character.deleteMany()
  await prisma.campaign.deleteMany()
  await prisma.encounter.deleteMany()

  console.log('🧹 Cleared existing data.')

  // Create Library Campaign (Inactive)
  const library = await prisma.campaign.create({
    data: {
      name: 'Character Library',
      active: false,
      characters: {
        create: libraryCharacters.map(char => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        }))
      }
    }
  })

  console.log(`📚 Created Library with ${libraryCharacters.length} presets.`)

  // Create Active Campaign
  const campaign = await prisma.campaign.create({
    data: {
      name: 'The Shadow of Everdawn',
      active: true,
      characters: {
        create: campaignCharacters.map((char) => ({
          name: char.name,
          type: char.type,
          class: char.class,
          race: char.race,
          hp: char.hp,
          maxHp: char.maxHp,
          armorClass: char.armorClass,
          initiative: char.initiative,
          initiativeRoll: char.initiativeRoll,
          speed: char.speed,
          activeTurn: char.activeTurn,
          imageUrl: char.imageUrl,
          attributes: JSON.stringify(char.attributes),
          level: char.level || 1,
        })),
      },
      logs: {
        create: [
          { content: 'The world of **The Shadow of Everdawn** is born.', type: 'Story' },
          { content: 'Campaign started in the Whispering Woods.', type: 'Story' },
          { content: 'Valerius rolled a **15** for initiative!', type: 'Roll' },
          { content: 'A group of goblins led by **Matriarch Zog** ambushes the party!', type: 'Combat' },
          { content: '**Matriarch Zog** roars, rallying her minions!', type: 'Story' },
          { content: '**Fae Wisp** flutters nervously above the fray.', type: 'Story' },
        ],
      },
    },
  })

  console.log(`🎉 Campaign "${campaign.name}" created with ${campaignCharacters.length} characters.`)

  // Create The Frozen Expanse Campaign (Inactive)
  const frozenCampaign = await prisma.campaign.create({
    data: {
      name: 'The Frozen Expanse',
      active: false,
      characters: {
        create: [
          {
            name: 'Bjorn',
            type: 'PLAYER',
            race: 'Human',
            class: 'Barbarian',
            imageUrl: '/avatars/fantasy_barbarian_male_1770266807624.png',
            hp: 20,
            maxHp: 20,
            armorClass: 14,
            initiative: 1,
            initiativeRoll: 0,
            speed: 30,
            attributes: JSON.stringify({ str: 18, dex: 12, con: 16, int: 8, wis: 10, cha: 10 }),
            activeTurn: false,
            level: 3,
          },
          {
            name: 'Lyra',
            type: 'PLAYER',
            race: 'Elf',
            class: 'Sorcerer',
            imageUrl: '/avatars/elf_female_1770267798836.png',
            hp: 14,
            maxHp: 14,
            armorClass: 12,
            initiative: 2,
            initiativeRoll: 0,
            speed: 30,
            attributes: JSON.stringify({ str: 8, dex: 14, con: 12, int: 10, wis: 10, cha: 18 }),
            activeTurn: false,
            level: 3,
          },
          {
            name: 'Ice Construct',
            type: 'NPC',
            race: 'Construct',
            class: 'Guardian',
            imageUrl: '/avatars/dwarf_mage_male_1770268698293.png',
            hp: 30,
            maxHp: 30,
            armorClass: 16,
            initiative: 0,
            initiativeRoll: 0,
            speed: 20,
            attributes: JSON.stringify({ str: 18, dex: 8, con: 18, int: 3, wis: 10, cha: 1 }),
            activeTurn: false,
            level: 4,
          },
          {
            name: 'Town Elder',
            type: 'NPC',
            race: 'Human',
            class: 'Commoner',
            imageUrl: '/avatars/wizard_male_1770266164795.png',
            hp: 8,
            maxHp: 8,
            armorClass: 10,
            initiative: 0,
            initiativeRoll: 0,
            speed: 30,
            attributes: JSON.stringify({ str: 9, dex: 10, con: 10, int: 14, wis: 16, cha: 12 }),
            activeTurn: false,
            level: 1,
          },
        ]
      },
      logs: {
        create: [
          { content: 'The winds howl across **The Frozen Expanse**.', type: 'Story' },
          { content: '**Bjorn** and **Lyra** arrive at the remote outpost.', type: 'Story' },
          { content: 'A strange **Ice Construct** blocks the path ahead.', type: 'Combat' },
        ]
      }
    }
  })

  console.log(`❄️ Campaign "${frozenCampaign.name}" created.`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
